# Use "plug'n'play" loader to hook up dependencies
nodeLinker: pnp

# Privacy & performance
enableTelemetry: false
enableGlobalCache: false

# Development experience
preferInteractive: true
progressBarStyle: patrick

# Build optimization
compressionLevel: mixed

# Git integration
changesetIgnorePatterns:
    - "**/*.tsbuildinfo"

# Use "exact match" to anchor versions for added dependencies
defaultSemverRangePrefix: ""

# Disable post-install scripts and guard from early updates
enableScripts: false
npmMinimalAgeGate: 30d
