apiVersion: 1

datasources:
    - name: Pyroscope
      uid: pyroscope
      type: grafana-pyroscope-datasource
      access: proxy
      url: http://pyroscope:42733
      isDefault: false
      editable: true
